id = "01K5S1TKRJV19ND6DXSGWS56Q2"
senate_website_key = "JCORA"
name = "Jt. Cong. Oversight Committee on the Alternative Dispute Resolution Act"
type = "joint"
congresses = [ 13, 14, 15, 16, 17, 18, 19, 20,]
