id = "01K5S1TKRKBMXF0T69MF9S3NAW"
senate_website_key = "LOVFA"
name = "Legislative Oversight Committee on the Visiting Forces Agreement"
type = "oversight"
congresses = [ 13, 14, 15, 16, 17, 18, 19, 20,]
