id = "01K5S1TKRHTJEFCEG44H88J3CX"
senate_website_key = "JCOCE"
name = "Jt. Cong. Oversight Committee Om the Ecological Solid Waste Management Act"
type = "joint"
congresses = [ 15, 16, 17, 18, 19, 20,]
