id = "01K5S1TKRBECX3E2YWAS9FM8JE"
senate_website_key = "COODA"
name = "Oversight Committee on the Official Development Assistance (ODA) Law"
type = "oversight"
congresses = [ 13, 14, 15, 16, 17, 18, 19, 20,]
