id = "01K5S1TKR98X5NPGT3GAF47P3M"
senate_website_key = "COCPI"
name = "Cong. Oversight on on the Proper Implementation of the National Internal Review Code"
type = "oversight"
congresses = [ 15, 16, 17, 18, 19, 20,]
