id = "01K5S1TKR7M3H4PW9EJTB7J8S6"
senate_website_key = "CECOW"
name = "Cong. Oversight on on the Ecological Solid Waste Management Act"
type = "oversight"
congresses = [ 13, 14, 15, 16, 17, 18, 19, 20,]
