id = "01K5S1TKR98X5NPGT3GAF47P3K"
senate_website_key = "COCPD"
name = "Cong. Oversight on on the Phil. Disaster Risk Reduction and Management Act of 2010"
type = "oversight"
congresses = [ 15, 16, 17, 18, 19, 20,]
