id = "01K5S1TKRSW4E6T0P9PA2ETPN8"
senate_website_key = "SCSCC"
name = "Subcommittee on the Sudden Collapse of the Cabagan-Sta. Maria Bridge in the Province of Isabela"
type = "subcommittee"
congresses = [ 19, 20,]
