id = "01K5S4AG1AJZ79AMDYG4MFHE7Q"
congress_number = 17
congress_website_key = 17
ordinal = "17th"
name = "17th Congress of the Philippines"
start_date = "2016-07-25"
start_year = 2016
end_date = "2019-06-04"
end_year = 2019
year_range = "2016-2019"
