id = "01K5S4AG1AJZ79AMDYG4MFHE7G"
congress_number = 10
congress_website_key = 10
ordinal = "10th"
name = "10th Congress of the Philippines"
start_date = "1995-07-24"
start_year = 1995
end_date = "1998-06-05"
end_year = 1998
year_range = "1995-1998"
