id = "01K5S4AG1AJZ79AMDYG4MFHE7S"
congress_number = 19
congress_website_key = 19
ordinal = "19th"
name = "19th Congress of the Philippines"
start_date = "2022-07-25"
start_year = 2022
end_date = "2025-06-11"
end_year = 2025
year_range = "2022-2025"
