id = "01K5S4AG1AJZ79AMDYG4MFHE7T"
congress_number = 20
congress_website_key = 103
ordinal = "20th"
name = "20th Congress of the Philippines"
start_date = "2025-07-28"
start_year = 2025
year_range = "2025-present"
