id = "01K5S4AG1AJZ79AMDYG4MFHE7H"
congress_number = 11
congress_website_key = 11
ordinal = "11th"
name = "11th Congress of the Philippines"
start_date = "1998-07-27"
start_year = 1998
end_date = "2001-06-08"
end_year = 2001
year_range = "1998-2001"
