id = "01K5S4AG1AJZ79AMDYG4MFHE7E"
congress_number = 8
congress_website_key = 8
ordinal = "8th"
name = "8th Congress of the Philippines"
start_date = "1987-07-27"
start_year = 1987
end_date = "1992-06-17"
end_year = 1992
year_range = "1987-1992"
