id = "01K5S4AG1AJZ79AMDYG4MFHE7K"
congress_number = 13
congress_website_key = 13
ordinal = "13th"
name = "13th Congress of the Philippines"
start_date = "2004-07-26"
start_year = 2004
end_date = "2007-06-08"
end_year = 2007
year_range = "2004-2007"
