id = "01K5S4AG1AJZ79AMDYG4MFHE7F"
congress_number = 9
congress_website_key = 9
ordinal = "9th"
name = "9th Congress of the Philippines"
start_date = "1992-07-27"
start_year = 1992
end_date = "1995-06-09"
end_year = 1995
year_range = "1992-1995"
