id = "01K5S4AG1AJZ79AMDYG4MFHE7R"
congress_number = 18
congress_website_key = 18
ordinal = "18th"
name = "18th Congress of the Philippines"
start_date = "2019-07-22"
start_year = 2019
end_date = "2022-06-01"
end_year = 2022
year_range = "2019-2022"
