id = "01K5S4AG1AJZ79AMDYG4MFHE7N"
congress_number = 15
congress_website_key = 15
ordinal = "15th"
name = "15th Congress of the Philippines"
start_date = "2010-07-26"
start_year = 2010
end_date = "2013-06-06"
end_year = 2013
year_range = "2010-2013"
