id = "01K5S1TKR38MZV3CD7SAXKY6TB"
senate_website_key = "PAQUI"
full_name = "Pimentel Jr., Aquilino Q."
name_suffix = "Jr"
last_name = "Pimentel"
middle_initial = "Q"
first_name = "Aquilino"
congresses = [ 13, 14, 15, 16, 17, 18, 19,]
