id = "01K5S1TKR4KBTJ6Z81S0Y4A052"
senate_website_key = "RRAMO"
full_name = "Revilla Jr., Ramon A."
name_suffix = "Jr"
last_name = "Revilla"
middle_initial = "A"
first_name = "Ramon"
congresses = [ 13, 14, 15, 16, 18, 19,]
