id = "01K5S1TKQZGCWG9MPHAV51MNZQ"
senate_website_key = "CALAN"
full_name = "Cayetano, Alan Peter \"Companero\" S."
aliases = [ "Companero",]
last_name = "Cayetano"
middle_initial = "S"
first_name = "Alan Peter"
congresses = [ 14, 15, 16, 17, 19, 20,]
