id = "01K5S1TKQYXMDG8MDDP8E0XX0H"
senate_website_key = "APAOL"
full_name = "Aquino IV, Paolo Benigno \"Bam\""
aliases = [ "Bam",]
name_suffix = "IV"
last_name = "Aquino"
first_name = "Paolo Benigno"
congresses = [ 16, 17,]
