id = "01K5S1TKR56ZN9DSSRMAZ65J3M"
senate_website_key = "ZJMIG"
full_name = "Zubiri, Juan Miguel F."
last_name = "Zubiri"
middle_initial = "F"
first_name = "Juan Miguel"
congresses = [ 15, 17, 18, 19, 20,]
