id = "01K5S1TKR1XPP68X120BWVMN3J"
senate_website_key = "GTEOF"
full_name = "Guingona III, Teofisto \"Tg\""
aliases = [ "Tg",]
name_suffix = "III"
last_name = "Guingona"
first_name = "Teofisto"
congresses = [ 15, 16,]
