id = "01K5S1TKR38MZV3CD7SAXKY6TC"
senate_website_key = "PEMMA"
full_name = "Pacquiao, Emmanuel \"Manny\" D."
aliases = [ "Manny",]
last_name = "Pacquiao"
middle_initial = "D"
first_name = "Emmanuel"
congresses = [ 17, 18,]
