id = "01K5S1TKR03RC0P7M9XF2GHMHV"
senate_website_key = "GSHER"
full_name = "Gatchalian, Sherwin T."
last_name = "Gatchalian"
middle_initial = "T"
first_name = "Sherwin"
congresses = [ 17, 18, 19, 20,]
