id = "01K5S1TKR1XPP68X120BWVMN3R"
senate_website_key = "LMANU"
full_name = "Lapid, Manuel \"Lito\" M."
aliases = [ "Lito",]
last_name = "Lapid"
middle_initial = "M"
first_name = "Manuel"
congresses = [ 13, 14, 15, 16, 18, 19, 20,]
