id = "01K5S1TKQYXMDG8MDDP8E0XX0J"
senate_website_key = "ASONN"
full_name = "Angara, Juan Edgardo \"Sonny\" M."
aliases = [ "Sonny",]
last_name = "Angara"
middle_initial = "M"
first_name = "Juan Edgardo"
congresses = [ 16, 17, 18, 19,]
