id = "01K5S1TKR1XPP68X120BWVMN3M"
senate_website_key = "HGREG"
full_name = "Honasan II, Gregorio B."
name_suffix = "II"
last_name = "Honasan"
middle_initial = "B"
first_name = "Gregorio"
congresses = [ 14, 15, 16, 17,]
