id = "01K5S1TKQYXMDG8MDDP8E0XX0M"
senate_website_key = "BMARI"
full_name = "Binay, Maria Lourdes Nancy S."
last_name = "Binay"
middle_initial = "S"
first_name = "Maria Lourdes Nancy"
congresses = [ 16, 17, 18, 19,]
