id = "01K5S1TKR4KBTJ6Z81S0Y4A057"
senate_website_key = "TFRAN"
full_name = "Tolentino, Francis \"Tol\" N."
aliases = [ "Tol",]
last_name = "Tolentino"
middle_initial = "N"
first_name = "Francis"
congresses = [ 18, 19,]
