id = "01K5S1TKR4KBTJ6Z81S0Y4A054"
senate_website_key = "SVICE"
full_name = "Sotto III, Vicente C."
name_suffix = "III"
last_name = "Sotto"
middle_initial = "C"
first_name = "Vicente"
congresses = [ 15, 16, 17, 18, 20,]
