id = "01K5S1TKR03RC0P7M9XF2GHMHS"
senate_website_key = "GCHRI"
full_name = "Go, Christopher Lawrence T."
last_name = "Go"
middle_initial = "T"
first_name = "Christopher Lawrence"
congresses = [ 18, 19, 20,]
