id = "01K5S1TKR2Z31VZS0XJ41QFK61"
senate_website_key = "MFERD"
full_name = "Marcos, Ferdinand \"Bongbong\" R."
aliases = [ "Bongbong",]
last_name = "Marcos"
middle_initial = "R"
first_name = "Ferdinand"
congresses = [ 15, 16,]
