id = "01K5S1TKQZGCWG9MPHAV51MNZX"
senate_website_key = "EJING"
full_name = "Ejercito-Estrada, Jinggoy P."
last_name = "Ejercito-Estrada"
middle_initial = "P"
first_name = "Jinggoy"
congresses = [ 13, 14, 15, 16, 19, 20,]
