id = "01K5S1TKR2Z31VZS0XJ41QFK64"
senate_website_key = "MRAMO"
full_name = "Magsaysay Jr., Ramon B."
name_suffix = "Jr"
last_name = "Magsaysay"
middle_initial = "B"
first_name = "Ramon"
congresses = [ 13,]
