id = "01K5S1TKQZGCWG9MPHAV51MNZW"
senate_website_key = "EFRAN"
full_name = "Escudero, Francis \"Chiz\" G."
aliases = [ "Chiz",]
last_name = "Escudero"
middle_initial = "G"
first_name = "Francis"
congresses = [ 14, 15, 16, 17, 19, 20,]
