id = "01K5S1TKR38MZV3CD7SAXKY6TD"
senate_website_key = "PFRAN"
full_name = "Pangilinan, Francis N."
last_name = "Pangilinan"
middle_initial = "N"
first_name = "Francis"
congresses = [ 13, 14, 15, 17, 18, 20,]
