id = "01K5S1TKR2Z31VZS0XJ41QFK66"
senate_website_key = "OSERG"
full_name = "Osmena III, Sergio R."
name_suffix = "III"
last_name = "Osmena"
middle_initial = "R"
first_name = "Sergio"
congresses = [ 13, 15, 16,]
