id = "01K5S1TKR03RC0P7M9XF2GHMHP"
senate_website_key = "ELUIS"
full_name = "Ejercito Estrada, Luisa \"Loi\" P."
aliases = [ "Loi",]
last_name = "Ejercito Estrada"
middle_initial = "P"
first_name = "Luisa"
congresses = [ 13,]
