id = "01K5S1TKQXA0NWQD2GJS73BEKS"
senate_website_key = "ABENI"
full_name = "Aquino III, Benigno S."
name_suffix = "III"
last_name = "Aquino"
middle_initial = "S"
first_name = "Benigno"
congresses = [ 14,]
