id = "01K5S1TKR03RC0P7M9XF2GHMHQ"
senate_website_key = "EVICT"
full_name = "Ejercito, Joseph Victor G."
last_name = "Ejercito"
middle_initial = "G"
first_name = "Joseph Victor"
congresses = [ 16, 17,]
