id = "01K5S1TKQZGCWG9MPHAV51MNZR"
senate_website_key = "CPIAS"
full_name = "Cayetano, Companera Pia S."
last_name = "Cayetano"
middle_initial = "S"
first_name = "Companera Pia"
congresses = [ 13, 14, 15, 16, 18, 19, 20,]
