id = "01K5S1TKR2Z31VZS0XJ41QFK60"
senate_website_key = "LPANF"
full_name = "Lacson, Panfilo M."
last_name = "Lacson"
middle_initial = "M"
first_name = "Panfilo"
congresses = [ 13, 14, 15, 17, 18, 20,]
