id = "01K5S1TKR56ZN9DSSRMAZ65J3J"
senate_website_key = "VMANU"
full_name = "Villar Jr., Manuel B."
name_suffix = "Jr"
last_name = "Villar"
middle_initial = "B"
first_name = "Manuel"
congresses = [ 13, 14,]
