id = "01K5S1TKR03RC0P7M9XF2GHMHT"
senate_website_key = "GRICH"
full_name = "Gordon, Richard \"Dick\" J."
aliases = [ "Dick",]
last_name = "Gordon"
middle_initial = "J"
first_name = "Richard"
congresses = [ 13, 14, 17, 18,]
