id = "01K5S1TKR4KBTJ6Z81S0Y4A055"
senate_website_key = "TANTO"
full_name = "Trillanes IV, Antonio \"Sonny\" F."
aliases = [ "Sonny",]
name_suffix = "IV"
last_name = "Trillanes"
middle_initial = "F"
first_name = "Antonio"
congresses = [ 14, 15, 16, 17,]
