name: Sync to Neo4j

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Neo4j sync script
      env:
        NEO4J_URI: ${{ secrets.NEO4J_URI }}
        NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
        NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
      run: |
        echo "Starting Neo4j sync..."
        python3 scripts/sync_to_neo4j.py --clear --yes
        echo "Neo4j sync completed successfully"

    - name: Report sync status
      if: always()
      run: |
        if [ $? -eq 0 ]; then
          echo "✅ Neo4j database successfully updated with latest data"
        else
          echo "❌ Neo4j sync failed. Please check the logs."
          exit 1
        fi